# Generated by Django 3.1.3 on 2020-11-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='New',
        ),
    ]
